# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - platzi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with gradle
      run: ./gradlew build

    - name: Deploy to Azure Web App
      uses: azure/PublishBuildArtifacts@1
      with:
        app-name: 'platzi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6e94105800a94835bcd3fe79d7977d3d }}
        package: '${{ github.workspace }}/target/*.jar'
